version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fingenie_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: fingenie_user
      DB_PASSWORD: your_password
      DB_NAME: fingenie
      DB_SSLMODE: disable
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: fingenie
    environment:
      POSTGRES_USER: fingenie_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: fingenie
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fingenie_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: 